version: "3"

services:
  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - oventemp-net
  grafana:
    image: grafana/grafana:7.1.5
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_DEFAULT_INSTANCE_NAME=grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    networks:
      - oventemp-net
    ports:
      - "3000:3000"
  oven-temp:
    image: bmiddha/oven-temp:edge
    restart: unless-stopped
    privileged: true
    networks:
      - oventemp-net
networks:
  oventemp-net:

volumes:
  influxdb:
  grafana:
