version: "3"

services:
  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    volumes:
      - influxdb:/var/lib/influxdb
    env_file: .env
    networks:
      - oventemp-net
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:7.1.5
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_DEFAULT_INSTANCE_NAME=grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp:25
    networks:
      - oventemp-net
    ports:
      - "3000:3000"
  renderer:
    image: grafana/grafana-image-renderer:2.0.0
    networks:
      - oventemp-net
    environment:
      ENABLE_METRICS: 'true'
  smtp:
   image: namshi/smtp
   restart: unless-stopped
   environment:
     - DISABLE_IPV6=1
   networks:
      - oventemp-net
networks:
  oventemp-net:

volumes:
  influxdb:
  grafana:
